# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all 
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: 
      pkg:
        - ruby-full
        - ruby-dev
        - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Import the public key used by the package management system
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present
  - name: Add MongoDB repository
    apt_repository: 
      repo: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' 
      state: present        
  - name: Install mongodb package
    apt:
      pkg: mongodb-org 
      state: latest 
      update_cache: yes
  - name: Enabled mongodb
    service:
      name: mongod
      state: started
      enabled: yes 
